### ISSUE TITLE
How do I auth with 2FA?

### ISSUE THREAD

**Issue by dtseiler** [tchellomello/python-ring-doorbell#161]
Hello, newbie here.

I've got a python 3.6 virtualenv on CentOS7 and trying just the basic authentication. Installed v2.8 via pip. I have 2FA set up on my Ring account. When I try the basic auth login from the README I get this error:

```
$ ./test.py
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    myring = Ring(username, password)
  File "/home/foo/doorbell/lib64/python3.6/site-packages/ring_doorbell/__init__.py", line 62, in __init__
    self._process_cached_session()
  File "/home/foo/doorbell/lib64/python3.6/site-packages/ring_doorbell/__init__.py", line 98, in _process_cached_session
    self._authenticate()
  File "/home/foo/doorbell/lib64/python3.6/site-packages/ring_doorbell/__init__.py", line 128, in _authenticate
    'Bearer {}'.format(self._get_oauth_token())
  File "/home/foo/doorbell/lib64/python3.6/site-packages/ring_doorbell/__init__.py", line 109, in _get_oauth_token
    self.auth_callback)
  File "/home/foo/doorbell/lib64/python3.6/site-packages/ring_doorbell/auth.py", line 28, in fetch_token
    return self.__fetch_token(username, password)
  File "/home/foo/doorbell/lib64/python3.6/site-packages/ring_doorbell/auth.py", line 55, in __fetch_token
    scope=OAuth.SCOPE)
  File "/home/foo/doorbell/lib64/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/home/foo/doorbell/lib64/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/home/foo/doorbell/lib64/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/home/foo/doorbell/lib64/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```

and then I get an SMS from Ring with the auth token. I don't see anything in the docs about how to do this for 2FA or setting up "app passwords" like Google does. Seems like I'm missing something fairly obvious that you all have figured out already.

**Comment by steve-gombos** [comment]
So the latest changes I pushed to this do have some support for 2FA, but it isn't really native yet.  Currently there is a callback method that can be passed into the Ring class to accept the 2FA input.  So I guess it depends how you are implementing this on your side.  If it is through HA, then there currently isn't a support for this, but if you are coding against the Ring class itself you can do something like this:

Here is an example:

```
from ring_doorbell import Ring


def callback():
    auth_code = input('2FA code:')
    return auth_code


username = input('Username:')
password = input('Password:')
ring = Ring(username, password, callback)
print(ring.devices)
```

The other alternative is to disable 2FA, authenticate with just basic credentials to get the access token/refresh token saved into the cache file, then you should be able to enable 2FA again since all calls to ring will either use the access token or refresh token.

**Comment by migster8** [comment]
Hello, could you please share an example of how to save the token into the cache file please? Many thanks

**Comment by migster8** [comment]
Sorry, Im a newbie to python and development in general. Think I got this to work by doing the following:
```
from ring_doorbell import Ring

username = input('Username:')
password = input('Password:')
cache_file = "link_to_cache_file"
ring = Ring(username, password, cache_file)
print(ring.devices)
```

**Comment by ZachBenz** [comment]
@steve-gombos For home automation purposes, seems like you could prompt the user for the auth-code the first go, and then rely on the tokens from there on out, correct?  I'm going to give this a try in my Indigo home automation server plugin...  (and thanks for getting this implemented!)

**Comment by steve-gombos** [comment]
@ZachBenz Yes, that is the behavior that I am seeing from their API currently.  So once you auth with the 2FA it will use refresh flow.  What I am not sure of is when/if they will revoke an issued token.  This would then go through the password flow again, which would prompt for the auth code again.

**Comment by ZachBenz** [comment]
@steve-gombos Got it - almost have it working in my Indigo plugin...though I did manage to make too many 2FA code requests in a short time while debugging, freezing me out of getting additional auth codes temporarily!  In case it is helpful to others, the exception thrown in that case is oauthlib.oauth2.rfc6749.errors.CustomOAuth2Error, where the exception string is: 

> u'error requesting 2fa service to send code'

If you try to make use of an official Ring app (e.g. the iOS app) and get a two factor auth code after seeing this exception, it gives a slightly more friendly error: Too many requests, limited to 10 requests every 10 minutes.  Took much longer than 10 minutes to escape my freeze out, though (to be fair, in debugging, I went _way_ over 10 requests in 10 minutes).

When not frozen out, the exception I'm seeing thrown when 2FA is enabled but the auth code provided is wrong is: oauthlib.oauth2.rfc6749.errors.MissingTokenError.  Due to the way Indigo plugins work, I can't pop up a dialog requesting an auth code dynamically in the callback, instead I have to try to login, find out I failed due to a missing auth code (which also causes the auth code to be sent), then prompt the user for the auth code at that point.

Once I have it going on my development system, I'll leave it running for a few weeks and see if we run into a revoked token during that time period.

**Comment by ZachBenz** [comment]
When trying to login to ring.com website, I get an even more informative error message due to my wanton debugging:

> You've entered too many invalid codes. To maintain security, you'll need to wait 24 hours before trying again

**Comment by ZachBenz** [comment]
@steve-gombos Ok, I have the test up and running with successful 2FA usage.  Going to leave it running and see what happens.

**Comment by dtseiler** [comment]
@steve-gombos thanks I'll give this a try later today. I'm just testing it via a script on a linux box, not using hass yet.

**Comment by dtseiler** [comment]
Yep this worked, for auth, thanks.

**Comment by idvorkin** [comment]
How do you get a 2FA code, do you need to trigger it from another device?

**Comment by idvorkin** [comment]
Also, can someone provide an example with the token caching? I can probably update the README.

**Comment by steve-gombos** [comment]
Test.py had these examples, but I have placed the minimum code in the readme now that 2FA is required.

**Comment by knlklabacka** [comment]
Sorry if this is not the greatest place to post this but I wanted to share with this group.  If anyone is interested in expanding on this or making adjustments feel free.  Below is what I'm using to get the verification code from my email to further automate the 2FA.  I have only tested this with gmail and it works. 

`def get_verification_code_from_email(self, email_host, email_username, email_password) 
    time.sleep(20)
    mail = imaplib.IMAP4_SSL(email_host)
    mail.login(email_username, email_password)
    mail.select("inbox")

    type, data = mail.search(None, 'ALL')
    mail_ids = data[0]

    id_list = mail_ids.split()
    first_email_id = int(id_list[0])
    latest_email_id = int(id_list[-1])

    for i in range(latest_email_id, first_email_id, -1):
        typ, data = mail.fetch(str(i), '(RFC822)')
        for response_part in data:
            if isinstance(response_part, tuple):
                (id, email_info,) = response_part
                msg = email.message_from_string(email_info.decode("utf-8"))
                email_subject = msg['subject']
                email_from = msg['from']

                if "New Login Attempt: Please Verify Your Account" in email_subject and 
                   "info@myaccount.ring.com" in email_from:

                   email_body = str(msg.get_payload()[0])

                   if "Your verification code:" in email_body:
                       start_of_code = email_body.split("Your verification code:", 1)[1]
                       code = start_of_code[0:7]
                       return code.strip()

    return False
`

I replaced the auth_code = input("2FA Code:") in the otp_callback() method with auth_code = get_verification_code_from_email() method above.

**Comment by dtseiler** [comment]
Just getting back to this project now with 0.6.0 and the stock test.py. I get prompted for user and password and then it fails on a function argument error. I'm never prompted for a 2FA code and one is not being sent by Ring.com like it used to be.

This is with python 3.6 in a fresh virtualenv on my CentOS 7 box.

```
$ python test.py
Username: abc
Password: xyz
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    main()
  File "test.py", line 31, in main
    auth = Auth(None, token_updated)
  File "/home/dts/doorbell/lib64/python3.6/site-packages/ring_doorbell/auth.py", line 21, in __init__
    client=LegacyApplicationClient(client_id=OAuth.CLIENT_ID), token=token
  File "/home/dts/doorbell/lib64/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 79, in __init__
    self.token = token or {}
  File "/home/dts/doorbell/lib64/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 129, in token
    self._client.populate_token_attributes(value)
  File "/home/dts/doorbell/lib64/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 492, in populate_token_attributes
    if 'access_token' in response:
TypeError: argument of type 'function' is not iterable
```

**Comment by dtseiler** [comment]
Oh it worked when I pulled the test.py from the master branch. The test.py in the 0.6.0 release tar.gz does not work.
