### ISSUE TITLE
Cannot get snapshot, while motion or ding event is active

### ISSUE THREAD

**Issue by budachst** [tchellomello/python-ring-doorbell#211]
I was trying to get a snapshot from the API while a motion event was on-going. That is the API had signalled a motion event and my app was waiting for the video to become available.

Calling get_snapshot() didn't do anything - it just seems to return nothing. Is this a limitation of the ring API, or is this working for someone?

**Comment by georgepstaylor** [comment]
As far as I’m aware, this is normal and if you tried this within the app, it would say something along the lines of “Ring Doorbell is Busy”

**Comment by budachst** [comment]
You mean the Ring app? I actually never tried this…, but I will check it out.

**Comment by georgepstaylor** [comment]
Yeah in the app! I’m fairly sure - but give it a go!

George Taylor
________________________________

**Comment by 4Dolio** [comment]
I also noticed I could not use the API twice simultaneously.  And I think I found a work around, the problem seems to be the user who is accessing is limited to one single session. In fact, I think my use of my main account by the API caused my phone account session to become corrupted, requiring me to logout and login to fix, may have been an edge case of my particular phone though.

So to work around, I made a new ring account just for each api instance I wanted to use.  Then from my main account I share access to all the devices to my api dedicated account.  Might be broadly helpful for this type of stuff.  Maybe worth mention in main api readme/howtoo?
