### ISSUE TITLE
Displaying the last video capture URL no longer works

### ISSUE THREAD

**Issue by DiljotSG** [tchellomello/python-ring-doorbell#78]
Attempting to display the last video capture URL as according to the documentation simply displays the following error message:

No handlers could be found for logger "ring_doorbell.doorbot"
False

I suspect that Ring has modified something on their end with the launch of their new products. Please advise.

**Comment by tchellomello** [comment]
Hello @DiljotSG, 
   Yes, Ring is now enforcing a premium subscription to be able to access the video recordings. 
   You are getting the "No handlers.." error because you don't have or did not initiate a logger facility. 
   A recent update on `python-ring-doorbell` library (https://github.com/tchellomello/python-ring-doorbell/commit/30a2f0c60479a780beae930742fb538dbb570f03)  introduced the ability to test if the account has a valid subscription. 
     If that is your case, you will need to subscribe it in order to get access to the videos. 

    If you think there room to expand our documentation please let me know or submit your patch and I'll be more than happy in merging it. 

  Thanks!

**Comment by tchellomello** [comment]
Closing as the questions has been addressed.

**Comment by paulmaunders** [comment]
I just got this same warning on a ring camera with a subscription, however it didn't prevent me from downloading a selection of recent recordings. It seemed to appear when I increased the limit from 10 to 100.

**Comment by paulmaunders** [comment]
It looks like this my error was caused because the output file already exists, however as @tchellomello described, I had not initiated a logger facility so was getting the generic logger error. Adding the following code will set up a logger, so you can see the real underlying error.
```
import logging
logging.basicConfig()
```
